### ISSUE TITLE
Port other Symfony1 plugns

### ISSUE THREAD

**Issue by thePanz** [LExpress/symfony1#100]
I am in the process ok porting other symfny1 plugins to be compatible with composer.
Here some of mine
 - sfFormI18nNumberPlugin : https://github.com/thePanz/sfFormI18nNumberPlugin
 - sfSQLToolsPlugin : https://github.com/thePanz/sfSQLToolsPlugin
 - sfCryptPlugin : https://github.com/thePanz/sfCryptPlugin

**Comment by j0k3r** [comment]
Thanks to share it!
Great, what kind of other plugins are working on?

_Since this issue insn't related to our fork I'll close it_

**Comment by thePanz** [comment]
I just ported those three plugins.
Is there an official list of "ported to composer" Symfony1 plugins?

**Comment by j0k3r** [comment]
Hum I don't think so.

**Comment by thePanz** [comment]
Could be ok to create a wiki-page where all the "ported" plugin get listed?
At least I don't feel confortable to "own" such plugins, what do  you think about merging our efforts to have a FriendsOfSymfony1 (FOS1) organization where let all the Symfony1 related works be unified?
