### ISSUE TITLE
sfBrowserBase posts unnamed submit fields

### ISSUE THREAD

**Issue by marekk** [LExpress/symfony1#106]
<input type="submit|image|button" /> and <button type="submit" /> are submitted even when without a name. They are not "successful controls": http://www.w3.org/TR/html401/interact/forms.html#h-17.13.2

Fix - change:
https://github.com/LExpress/symfony1/blob/master/lib/util/sfBrowserBase.class.php#L782
to
if ($item->getAttribute('name')) {
  $this->parseArgumentAsArray($item->getAttribute('name'), $item->getAttribute('value'), $arguments);
}

**Comment by j0k3r** [comment]
Thanks for that, could you submit a PR with your fix?
