### ISSUE TITLE
Does not work when not using composer - or docs needed

### ISSUE THREAD

**Issue by Xosofox** [LExpress/symfony1#107]
I've been trying to integrate your project into an old dinosaur project that needs to be upgraded.

Two issues:

a) If I want to be using composer, how should I autoload/boot the project? Change ProjectConfigurationClass to what? -> Hint/example in the doc would be helpful

b) if not using composer but just clone into lib/vendor (or even another directory), due to the missing composer-autoload, the "Swift" class is unknown and symfony's generated `cache/frontend/config/config_factories.yml.php`will try to load it from `/vendor/swiftmailer/lib` where you are not keeping it anymore

```php
#taken from generated /cache/frontend/dev/config/config_factories.yml.php
  if (!class_exists('Swift')) {
    $swift_dir = sfConfig::get('sf_swiftmailer_dir',   sfConfig::get('sf_symfony_lib_dir').'/vendor/swiftmailer/lib');
    require_once $swift_dir.'/swift_required.php';
  }
```

Or did I miss something? If so, please help, and I'll put it in PR for the docs to save the next n00b like me from having the same issue

**Comment by Xosofox** [comment]
Ahhh!!

The always so helpful Propel Docs made my day:

https://github.com/propelorm/sfPropelORMPlugin

explains the composer approach in more detail

So, some "composer installation" hints taken from there might be helpful.

Still the problem persists that it won't work without composer

**Comment by j0k3r** [comment]
Hum yes, we need more doc about that point. I was almost sure that we written that somewhere.
Anyway.

You should add the autoload.php from composer in your `ProjectConfiguration` :

```php
require_once dirname(__DIR__).'/lib/vendor/autoload.php';
```

And if you are not using it with Composer don't forget to initialize & update submodule using `git submodule update --init` ([swiftmailer](https://github.com/LExpress/symfony1/tree/master/lib/vendor) and [doctrine](https://github.com/LExpress/symfony1/tree/master/lib/plugins/sfDoctrinePlugin/lib/vendor) are here as legacy)
