### ISSUE TITLE
LExpress/doctrine1 and Doctrine.php

### ISSUE THREAD

**Issue by coldlamper** [LExpress/symfony1#108]
Why is the file /lib/Doctrine.php left out.
It leaves out 

```php
class Doctrine extends Doctrine_Core
{
}
```

which breaks some code like Doctrine::getTable.

**Comment by j0k3r** [comment]
As the comment in the class says:

> This class only exists for backwards compatability. All code was moved to Doctrine_Core and this class extends Doctrine_Core

This isn't something we made, it had been done in the main doctrine1 repo (as far as I remember it was changed when the 1.2.0 goes out).

https://github.com/doctrine/doctrine1/blob/master/lib/Doctrine.php

You need to update all your code where you are using `Doctrine:` to `Doctrine_Core::`

**Comment by coldlamper** [comment]
Ahh. Thanks.  There are some plugins like sfGuardDoctrinePlugin which I would rather not edit. I think it will be easier to just add

 class Doctrine extends Doctrine_Core
{
}
