### ISSUE TITLE
Doctrine_Core::HYDRATE_ON_DEMAND not working

### ISSUE THREAD

**Issue by bitak1** [LExpress/symfony1#109]
I upgraded my project from Symfony 1.4.20, where following query was working just fine, unfortunately now HYDRATE_ON_DEMAND doesn't work anymore.

```php
        $uctuj_od_dt = "2015-10-01 00:00:00";
        $q_ucty = Doctrine_Query::create()
                ->select()
                ->from('Ucet')
                ->where('od >= ?', $uctuj_od_dt)
        ;

        $ucty = $q_ucty->execute(array(), Doctrine_Core::HYDRATE_ON_DEMAND);
//        $ucty = $q_ucty->execute();

        $counter = 0;
        foreach ($ucty_tel as $ucet) {
            // doing something
            $counter++;
        }
```

If I use `Doctrine_Core::HYDRATE_ON_DEMAND` the `$counter` ends up to be only 2, instead of many hundreds, which are in database. If I use only `$ucty = $q_ucty->execute();` then I get all the results as expected, but then it consumes to much memory on the server... I also noticed, that if I use query without the `where` clause, then `$ucty = $q_ucty->execute(array(), Doctrine_Core::HYDRATE_ON_DEMAND);` works fine.

**Comment by kipit** [comment]
It's seems to be a Doctrine only issue. This code snippet don't use anything from Symfony. You may try to upgrade to https://github.com/LExpress/symfony1 and then take a look to a Doctrine 1 fork like https://github.com/LExpress/doctrine1

**Comment by kipit** [comment]
Anyway, what Doctrine version do you use? With what version of PHP?

**Comment by fidelio314** [comment]
Hello, i found a similar issue, using the doctrine1 fork of LExpress.

I have a pager built. With NbResults 600 (in an example)
then i user the method: ` $pager->getResults(Doctrine_Core::HYDRATE_ON_DEMAND)`

then i have a while loop:

```
while ($oCustomer = $oCustomers->current()) {
.....
....
     $oCustomer->free();
     $oCustomers->next();
}
```

i would suppose to have 600 loops.

i actually have 2!

rolled back in symfony1.4 i confirm having 600 loops.

do you have any idea on the subject? 

thanks!

**Comment by IN2javierperez** [comment]
This happens to me also. Some tip or solution for this?

**Comment by miniche** [comment]
I have never encountered this problem in dev/prod environment at work. 

Currently, I'm not working on symfony 1.5 projects anymore, as all new projects has been written in Symfony 2/3.

If it's a Doctrine 1 issue, you can create an issue or send us a PR to fix it here: https://github.com/LExpress/doctrine1

Have you checked original Doctrine 1 issue tracker?

**Comment by fidelio314** [comment]
hi! noop i haven't found something similar into the Doctrine 1 issue tracker.

i created an issue on the doctrine1 fork repo

thanks
