### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by timmipetit** [LExpress/symfony1#118]
Hi, we're also maintaining a Symfony1 fork based on yours. Recently we've made some changes to fix PHP7 compatibility. You can see our internal PR here: https://github.com/Recras/symfony1/pull/11
We've diverged quite a bit from you're master, so unfortunately I wasn't able to create a PR for you easily. If you're interested in using our changes, feel free.
btw: we decided to stop testing for PHP5.3

**Comment by j0k3r** [comment]
Looks interesting ! Thanks.

We'll check that https://github.com/LExpress/symfony1/compare/master...Recras:master

**Comment by zkiiito** [comment]
Hey guys,
What do you think, when could we get some update on this?
Would love to have a PHP7 compatible release!
Thanks
