### ISSUE TITLE
PHP Warning:  require_once(/Doctrine/Core.php)

### ISSUE THREAD

**Issue by hmartinsceven** [LExpress/symfony1#145]
Hello everyone,

I am using symfony1.4 in some of my projects. After upgrading my OS and PHP to 7 version, I am facing problems with symfony1.4, I need to keep my projects a live without upgrading symfony to 2 version.
And I also use Doctrine in all of them.

Now I am trying to move one of my project to lexpress/symfony1 fork.

This is how I am doing:

- 1. delete vendor/symfony
- 2. run 
- 2.1 composer require lexpress/symfony1 "1.5.*"
- 2.2 composer install
- 3. changed ProjectConfiguration.class.php line 3 to require_once dirname(__FILE__).'/../lib/vendor/lexpress/symfony1/lib/autoload/sfCoreAutoload.class.php';
- 4. trying to do symfony cc, but now I am receiving this error:
- PHP Warning:  require_once(/Doctrine/Core.php)

_I attached my terminal screen after run symfony cc cmd.
Also sfDoctrinePlugin/lib/vendor/doctrine is empty as other print screen is showing._

Some way to overcome this problem ? 
Thanks in advance.

![vendor-doctrine-empty](https://cloud.githubusercontent.com/assets/3170222/21221930/52a0de4e-c2b7-11e6-8e2c-ec5c1410f4c8.png)
![symfony-cc](https://cloud.githubusercontent.com/assets/3170222/21221931/52a1bf30-c2b7-11e6-9210-8569ee439c61.png)

**Comment by shastik** [comment]
Hi I think you forgot to install Doctrine 

Install Doctrine1 via composer (https://github.com/LExpress/doctrine1) and set composer autoloader in ProjectConfiguration.class.php

Similar issue: https://github.com/LExpress/symfony1/issues/76

**Comment by j0k3r** [comment]
@shastik is right.
You should either:
- do `composer require lexpress/doctrine1 "1.3.*"`
- or init your git submodule

Better option is the first one.

**Comment by hmartinsceven** [comment]
Where I need to run composer require lexpress/doctrine1 "1.3.*", inside vendor folder? 

Excuse the seemingly easy question..
@shastik  @j0k3r

**Comment by j0k3r** [comment]
In your root folder, the same way you did for `composer require lexpress/symfony1 "1.5.*"`

**Comment by hmartinsceven** [comment]
@j0k3r after run composer require lexpress/symfony1 "1.5.*" I moved all generated folders and files to vendor.. 

Maybe what I did before is wrong, that’s the reason I'm asking.
I attached my vendor folder print screen.
![vendor-folder](https://cloud.githubusercontent.com/assets/3170222/21222659/ed2c7e34-c2ba-11e6-9dbf-ee0eb1eb0f3c.png)

**Comment by j0k3r** [comment]
Could you share your composer.json?

You should define a line about the vendor directory so composer will put all vendor files in it:

```json
{
    "name": "myproject",
    "require": {
        "lexpress/symfony1": "1.5.*",
        "lexpress/doctrine1": "1.3.*"
    },
    "config": {
        "vendor-dir": "lib/vendor/"
    },
}
```

**Comment by hmartinsceven** [comment]
composer.json is placed in my lib folder, and here is the content
{
    "require": {
        "lexpress/symfony1": "1.5.*"
    }
}

I understand now that I should not moved the folder generated by composer to vendor folder, but these

 "config": {
        "vendor-dir": "lib/vendor/"
    },

Will solve that, if I understand it well.
Sorry, but I have no knowledge of composer for now.

I need to run composer after replace content in my composer.json, right?
Thanks in advance.

**Comment by hmartinsceven** [comment]
After replace composer.json I run composer update I receive:
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing swiftmailer/swiftmailer (v5.4.4)
    Loading from cache

  - Installing lexpress/symfony1 (v1.5.8)
    Loading from cache

  - Installing lexpress/doctrine1 (v1.3.4)
    Loading from cache

lexpress/symfony1 suggests installing propel/sf-propel-o-r-m-plugin (Propel plugin)
lexpress/symfony1 suggests installing psr/log (Psr logger)

but doctrine1 is not place in lib/vendor/lexpress/ or lib/vendor/

**Comment by j0k3r** [comment]
composer.json must be in the root folder, not in lib folder.

**Comment by hmartinsceven** [comment]
@j0k3r 

I reversed everything I had done wrong up here, and ran again.

Now I am facing this error:
Class 'Doctrine' not found (sfGuardValidatorUser.class.php)

**Comment by hmartinsceven** [comment]
@j0k3r 

do I need to replace all occurrences Doctrine to Doctrine_Core?

**Comment by j0k3r** [comment]
If you didn't touch the sfDoctrineGuard bundle, you should use that one instead https://github.com/LExpress/sfDoctrineGuardPlugin

**Comment by hmartinsceven** [comment]
@j0k3r I understood, but I use some other actions witch calls Doctrine, do I need to replace to Doctrine_Core instead Doctrine, right?

**Comment by j0k3r** [comment]
Yes you have to.

**Comment by hmartinsceven** [comment]
@j0k3r many thanks to your time.

**Comment by somoza** [comment]
> { "name": "myproject", "require": { "lexpress/symfony1": "1.5.*", "lexpress/doctrine1": "1.3.*" }, "config": { "vendor-dir": "lib/vendor/" }, }

You must remove the coma in the last bracket in this way...

```
{
    "name": "oraculo",
    "require": {
        "lexpress/symfony1": "1.5.*",
        "lexpress/doctrine1": "1.3.*"
    },
    "config": {
        "vendor-dir": "lib/vendor/"
    }
}
```

**Comment by marcelnagm** [comment]
I have created 
/**
 * Description of Doctrine
 *
 * @author marcel
 */
class Doctrine extends Doctrine_Core {
    //put your code here
}
at lexpress/doctrine1/lib/Doctrine/Doctrine.php
Solved my issues

**Comment by gigo6000** [comment]
> If you didn't touch the sfDoctrineGuard bundle, you should use that one instead https://github.com/LExpress/sfDoctrineGuardPlugin

I think is easier to keep using the old version (in your project) of the `sfDoctrineGuardPlugin` and just search replace the `Doctrine` occurrences with `Doctrine_Core`. This new version of the plugin includes some major changes like adding new columns to the `sfGuardUser` table: `first_name`, `last_name` and `email_address`.
