### ISSUE TITLE
fix notice "A non well formed numeric value encountered in .../yaml/sfYamlInline.class.php(137) : runtime-created function on line 1" (php 7.1)

### ISSUE THREAD

**Issue by shaula** [LExpress/symfony1#150]
Warning: A non-numeric value encountered in .../vendor/lexpress/symfony1/lib/yaml/sfYamlInline.class.php(137) : runtime-created function on line 1
Call Stack
No	Time	Memory	Function	Location
1	0.0002	378120	{main}( )	.../index.php:0
2	0.2656	10592184	sfContext->dispatch( )	.../index.php:18
3	0.2656	10592184	sfFrontWebController->dispatch( )	.../sfContext.class.php:173
4	0.2658	10602248	sfController->forward( )	.../sfFrontWebController.class.php:48
5	0.2703	11161992	sfFilterChain->execute( )	.../sfController.class.php:238
6	0.2704	11162472	sfRenderingFilter->execute( )	.../sfFilterChain.class.php:53
7	2.2917	36448664	sfWebResponse->send( )	.../sfRenderingFilter.class.php:51
8	2.2920	36449760	sfWebResponse->sendContent( )	.../sfWebResponse.class.php:397
9	2.2920	36449760	sfResponse->sendContent( )	.../sfWebResponse.class.php:387
10	2.2920	36449888	sfEventDispatcher->filter( )	.../sfResponse.class.php:97
11	2.2920	36449888	sfWebDebugLogger->filterResponseContent( )	.../sfEventDispatcher.class.php:116
12	2.2929	36469120	sfWebDebug->injectToolbar( )	.../sfWebDebugLogger.class.php:174
13	2.3513	36825472	sfWebDebug->asHtml( )	.../sfWebDebug.class.php:176
14	2.3513	36826264	sfWebDebugPanelConfig->getPanelContent( )	.../sfWebDebug.class.php:204
15	2.3519	36862488	sfWebDebugPanelConfig->formatArrayAsHtml( )	.../sfWebDebugPanelConfig.class.php:53
16	2.3519	36866168	sfYaml::dump( )	.../sfWebDebugPanelConfig.class.php:78
17	2.3521	36873472	sfYamlDumper->dump( )	.../sfYaml.class.php:132
18	2.3521	36873512	sfYamlDumper->dump( )	.../sfYamlDumper.class.php:51
19	2.3524	36873816	sfYamlDumper->dump( )	.../sfYamlDumper.class.php:51
20	2.3524	36873816	sfYamlInline::dump( )	.../sfYamlDumper.class.php:37
21	2.3524	36873816	sfYamlInline::dumpArray( )	.../sfYamlInline.class.php:93
22	2.3524	36874792	array_reduce ( )	.../sfYamlInline.class.php:137
23	2.3525	36874792	__lambda_func( )	.../sfYamlInline.class.php:137

**Comment by vendethiel** [comment]
see #148

**Comment by j0k3r** [comment]
What should I do with that?

**Comment by e1himself** [comment]
This should be closed probably. As the referenced PR is merged now.
