### ISSUE TITLE
Error on Form Saving

### ISSUE THREAD

**Issue by NoahTwine** [LExpress/symfony1#157]
I'm trying to use LExpress to move my Symfony 1.4 application from PHP 5.6 to PHP 7. So far it's working beautifully.

However, when I go to save any form I get the following error:

`PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /lib/vendor/symfony/lib/form/addon/sfFormObject.class.php on line 281`

As a result, all fields are saved with the value null.

Any tips here? I could obviously just manually rewrite the relevant portions of sfFormObject.class.php but I'd like to avoid rewriting vendor classes if possible.

Thank you.

**Comment by j0k3r** [comment]
There is no such `preg_replace` in our fork.
See https://github.com/LExpress/symfony1/blob/master/lib/form/addon/sfFormObject.class.php#L281

Maybe your symfony version isn't well loaded.
