### ISSUE TITLE
Documentation on using on a existing project.

### ISSUE THREAD

**Issue by rsantellan** [LExpress/symfony1#164]
Hi, 

I have inherit a legacy app on Symfony 1.4 the migration to a new version of Symfony will be really really long. So when I found this project is a real life safer for me!
Is there any documentation on how to exchange the symfony 1.4 with this project? Because 1.4 didn't have composer? I just have to copy all the files on the right folders?

Regards

**Comment by arendvw** [comment]
There are the upgrade notes here:

https://github.com/LExpress/symfony1/blob/master/UPGRADE.md

Keep in mind that there are a few things that are not backwards compatible.

**Comment by rsantellan** [comment]
It has installed all, should I remove old lib/vendor?
I have this error: Fatal error: Class 'Doctrine' not found in /vagrant/lib/model/ on calling Doctrine::getTable('usuario')

I have to do the use statements now? 

Regards.

**Comment by j0k3r** [comment]
No, it's because you've to use `Doctrine_Core` instead of `Doctrine` now: https://github.com/LExpress/doctrine1/commit/1b9372c47af72c722a177cddcc941667739dffd6

**Comment by rsantellan** [comment]
thanks @j0k3r do I have to remove lib/vendor?
Regards!

**Comment by VolCh** [comment]
Yes. If in your /lib/vendor there are only packages that now in /vendor (from  composer.json), only symfony for example.

**Comment by rsantellan** [comment]
Thanks for all the help! Now I have it running!
