### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by Jonathan-Bryan** [LExpress/symfony1#165]
Hi, not sure if this is the right place to ask for support but I can't find anywhere else to ask!

My composer.json...

```
{
    "name": "ifds.3",
    "require": {
        "lexpress/symfony1": "1.5.*",
        "lexpress/doctrine1": "1.3.*"
    },
    "config": {
        "vendor-dir": "lib/vendor/"
    }
}
```

But the doctrine vendor folder is empty...

ifds.3/lib/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine

And the Doctrine vendor code is here...

ifds.3/lib/vendor/lexpress/doctrine1

If I move the contents of doctrine1 to sfDoctrinePlugin/lib/vendor/doctrine it seems to work but I guess, I'm not supposed to be doing that manually?

Same sort of thing for swiftmailer.

Am I missing something? I'm new to composer.

Any help much appreciated!

**Comment by Jonathan-Bryan** [comment]
I think I figured it out. I add...

require_once dirname(__FILE__).'/../lib/vendor/autoload.php';

...to the top of ProjectConfiguration.class.php

Is that the recommended way?

**Comment by j0k3r** [comment]
It is.
