### ISSUE TITLE
Swift.php include problem after autoload

### ISSUE THREAD

**Issue by juansss** [LExpress/symfony1#172]
Hi guys! I have this error after installing the project
`
Warning: require_once(/home/juan/Desarrollo/securepaysmile/lib/vendor/lexpress/symfony1/lib/vendor/swiftmailer/classes/Swift.php): failed to open stream: No such file or directory in /home/juan/Desarrollo/securepaysmile/cache/backend/dev/config/config_factories.yml.php on line 134

Fatal error: require_once(): Failed opening required '/home/juan/Desarrollo/securepaysmile/lib/vendor/lexpress/symfony1/lib/vendor/swiftmailer/classes/Swift.php' (include_path='.:/usr/share/php') in /home/juan/Desarrollo/securepaysmile/cache/backend/dev/config/config_factories.yml.php on line 134
`

My project configuration with the autoload required
`require_once dirname(__FILE__).'/../lib/vendor/autoload.php';
sfCoreAutoload::register();`

And my composer.json is
`{
    "name": "test",
    "require": {
        "lexpress/symfony1": "1.5.*",
        "lexpress/doctrine1": "1.3.*",
	"lexpress/sf-doctrine-guard-plugin": "^1.5"
    },
    "config": {
        "vendor-dir": "lib/vendor/"
    }
}`

Any suggestions?

Thanks! in advance

**Comment by rsantellan** [comment]
@juansss I did this for working. First my composer.json

```
{
    "name": "s1",
    "minimum-stability": "stable",
    "type": "project",
    "license": "MIT",
    "require": {
        "lexpress/symfony1": "^1.5",
        "lexpress/doctrine1": "^1.3",
        "lexpress/sf-doctrine-guard-plugin": "^1.5",
        "lexpress/sf-web-browser-plugin": "^1.2",
        "psr/log": "^1.0"
    }
}
```

My ProjectConfiguration.class.php is:
```
<?php

//require_once dirname(__FILE__).'/../lib/vendor/symfony/lib/autoload/sfCoreAutoload.class.php';
require_once __DIR__.'/../vendor/autoload.php';
sfCoreAutoload::register();

class ProjectConfiguration extends sfProjectConfiguration
{
  public function setup()
  {
    $this->enableAllPluginsExcept();      
    //$this->enablePlugins(array('sfCaptchaGDPlugin'));
  }
}
```
Hope it helps!

**Comment by juansss** [comment]
@rsantellan yes! Thank you!

**Comment by rsantellan** [comment]
@juansss I believe you can close the issue now :)

**Comment by wildanm** [comment]
AwWqfw

**Comment by wildanm** [comment]
AwWqfw
