### ISSUE TITLE
psr/log dev dependency

### ISSUE THREAD

**Issue by rsantellan** [LExpress/symfony1#173]
Hi, is that dependency used on the repository? It was intended for changing the log library?
Regards.

**Comment by GromNaN** [comment]
It makes the sfLogger compatible with [PSR-3](http://www.php-fig.org/psr/psr-3/). This is useful when using libraries that supports this standard interface.

**Comment by rsantellan** [comment]
@GromNaN so I can use monolog? Or other library to log? Is there an example of this? Thanks in advance!

**Comment by GromNaN** [comment]
Yes you can, thanks to the [sfPsrLoggerAdapter](https://github.com/LExpress/symfony1/blob/master/lib/log/sfPsrLoggerAdapter.class.php).
