### ISSUE TITLE
1.5.10 and php 7.1

### ISSUE THREAD

**Issue by PapaLimaZulu** [LExpress/symfony1#180]
Hi All,
does version 1.5.10 support php7.1?
I get
`Fatal error: Uncaught Error: Call to undefined function xml_parser_create() in /home/plz/dev/git/sk3/lib/vendor/phing/phing/classes/phing/parser/ExpatParser.php on line 81
`
when trying to do:
`symfony propel:insert-sql`

thanks!

**Comment by PapaLimaZulu** [comment]
I see... the problem is not Symfony but Phing.

**Comment by e1himself** [comment]
@PapaLimaZulu It fails because you're missing **xml-parser** extension and not because of PHP version.
