### ISSUE TITLE
Symfony Form Formatter - Problem rendering HTML attributes

### ISSUE THREAD

**Issue by filipe-carvalho** [LExpress/symfony1#193]
Hello
I am facing a problem when creating a form formatter inside symfony, i am using symfony 1.4 and the latest version of lexpress v1.5.11

# MY CODE

I have a custom formatter for a form (imagine this class: sfWidgetFormSchemaFormatterTest.class)
I am using this custom created formatter class inside a form class (Imagine Form named TestForm.class.php)

I wanted to passed HTML attributes to a certain widget inside the form class. For sake of example lets imagine that i have a a field "email_address" inside this testForm.class.php and i want to add a custom HTML class. I know that is possible to add a class inside the Form using this code:

` $this->widgetSchema['email_address']= = new sfWidgetFormInputText(array(),array'class' => 'someClass));`

But i wanted to add a custom HTML attribute inside the construct method of the formatter, and this is what i am doing;

```
class sfWidgetFormSchemaFormatterTest extends sfWidgetFormSchemaFormatter
{
  function __construct(sfWidgetFormSchema $widgetSchema)
  {
    parent::__construct($widgetSchema);

    foreach ($this->getWidgetSchema()->getFields() as $name => $field)
    {
      
      $id = $this->widgetSchema->generateId($this->widgetSchema->generateName($name));
   
      if(array_key_exists('class', $field->getAttributes()))
      {
        $attributes = $field->getAttributes();
        $field->setAttribute('class' , 'someClass '.$attributes['class']);
      }
      else
      {
         $field->setAttribute('class', 'someClass');
      }
    }
  }
}
```

# Template

For the render of the form in the template i rendering the hidden fields by calling the method renderingHiddingFields and rendering the fields of the form by renderRow, see the next example:
```
<form action="<?php echo url_for('@sf_guard_signup' ) ?>" method="post">
  <!--[01] - HIDDEN FIELDS-->
  <?php echo $form->renderHiddenFields(); ?>
  <?php echo $form["_csrf_token"]->renderError() ?>

  <!--[02] - FIELDS --> 
  <?php echo $form["email_address"]->renderRow(); ?>
  <?php echo $form["password"]->renderRow(); ?>
  **... MORE FIELDS RENDER BY THIS WAY**


  <!--[03] - SUBMIT-->
  <div class="form-group pt-3 m-0">
    <button type="submit" class="btn btn-lg bg-success text-white font-weight-bold w-100 biome-guard-submit-button"><?php echo __('Confirm', null, 'sf_guard') ?></button>
  </div>   

</form>
```

# PROBLEM DESCRIPTION

Using all the code showed above i am facing a bug. On the first field that is rendered, the HTML attributes inserted in Formatter doesnt exists, but on the other fields that HTML attributes seems to appear.

THIS IS HTML OUTPUT OF MY FIRST FIELD
`<input type="text" name="signup[email_address]" />`

THIS IS HTML OUTPUT OF MY OTHER FIELDS
`<input type="text" name="signup[password]" class="someClass"/>`

# THE SOLUTION SO FAR

Passed many hours trying figuring out a solution, and this is what i had so far

## First Solution: 
If in the template i render the error of global hidden field (_crsf_token) the problem dissapears, but i don't understand why 

So in the template i simple added following :
`<?php echo $form["_csrf_token"]->renderError() ?>`

## Second Solution:
 If i added the HTML attributes directly in the form class the problem dems to dissapear too, however i didnt want to use this way because is not a good programming practice.

# OUTPUT OF THE SOLUTION AND THE DESIRE OUTPUT

THIS IS HTML OUTPUT OF MY FIRST FIELD
`<input type="text" name="signup[email_address]" class="someClass" />`

THIS IS HTML OUTPUT OF MY OTHER FIELDS
`<input type="text" name="signup[password]" class="someClass"  />`

**_Can you please help me ? is possible this to be a bug of symfony, or the lexpress, or i am doing something wrong ?_**

# Thank You Very Much :)

**Comment by mkopinsky** [comment]
Would you be able to put up a functioning repo or gist illustrating the problem? I can conceptually follow what you're describing, and the behavior certainly is unexpected, but to really dive in and try to find the root cause I need to have something I can run and inspect.

**Comment by filipe-carvalho** [comment]
Hi mkopinsky, 

I now understand what is causing this problem
I tested your solutions and the fix my problem, i am really appreciated for your time and kind help

Thank You
