### ISSUE TITLE
Having problem with sfPropelPlugin using FormFilters for the backend admin generator

### ISSUE THREAD

**Issue by JurekR** [LExpress/symfony1#194]
Hi,

thanks for your symfony 1.5! Now I am using sfPropelPlugin, but since some changes in PHP, the plugin throws the following error, if I try to use a admin generator filter:
`You must define a "addColumnCriteria" method to be able to filter with the "content" field.`

And seems to fail at:
SF_SYMFONY_LIB_DIR/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php line 135

At this place, it does not detect my filter methods in /lib/filter/ContentFormFilter.class.php, which are named like:
`public function addContentColumnCriteria(Criteria $c, $field, $value)`

Do you know how I can fix this? 

I also found a recent sfPropelORMPlugin, but my symfony project seems to expect a "sfPropelPlugin" instead... Any idea how to make it work with the recent sfPropelORMPlugin?

Thanks

**Comment by JurekR** [comment]
Ok, nevermind, I added sfPropelORMPlugin 1.7.1 now to my symfony 1.5 project, using this manual:
https://github.com/propelorm/sfPropelORMPlugin

Even seems to run with sfGuardPlugin 👍

**Comment by j0k3r** [comment]
Good to know!
