### ISSUE TITLE
Make sfLogger compliant with PSR3 (logger) and use it as this

### ISSUE THREAD

**Issue by GromNaN** [LExpress/symfony1#32]
The PSR-3 describe a common interface for loggers for interoperability.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

Option1: Make sfLogger implement the LoggerInterface. This adds a mandatory dependency, but allow to replace the logger by any other library (like Monolog).

Option2: Add an abstraction layer on top of the sfLogger.

**Comment by miniche** [comment]
Related to #88 

Can we close this (great) idea or anyone want to work on this? 😄
