### ISSUE TITLE
Can't use configureDoctrine function anymore

### ISSUE THREAD

**Issue by faboo03** [LExpress/symfony1#42]
On sf1.4, the following code was inside sfDoctrinePluginConfiguration.class.php  allowing me to use configureDoctrine() inside my ProjectConfiguration.class.php
```
 if (method_exists($this->configuration, 'configureDoctrine')) {
     $this->configuration->configureDoctrine($manager);
 }
```

I understand that now I should use the dispatcher on doctrine.configure event, but for retrocompatibility, it should be back or at least mentionned in migration doc.

**Comment by cburyta** [comment]
Agree, this one caught me also, specifically when leveraging the config for soft delete features. For example this is the example of my ProjectConfiguration before and after to resolve so my configureDoctrine was called.

**Before**

```php
class ProjectConfiguration extends sfProjectConfiguration {
  public function setup()
  {
      $this->enablePlugins([
          'sfDoctrinePlugin',
          'sfDoctrineGuardPlugin'
      ]);
  }

  public function configureDoctrine(Doctrine_Manager $manager)
  {
      // Enable callbacks so that softDelete behavior can be used
      $manager->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, true);
  }
}
```

**After** (note the use of static now on the method to confirm to strict standards for call_user_func)

```php
class ProjectConfiguration extends sfProjectConfiguration {
  public function setup()
  {
      $this->enablePlugins([
          'sfDoctrinePlugin',
          'sfDoctrineGuardPlugin'
      ]);

      $this->dispatcher->connect('doctrine.configure', array('ProjectConfiguration', 'configureDoctrine'));
  }

  public static function configureDoctrine(sfEvent $event)
  {
      $manager = $event->getSubject();

      // Enable callbacks so that softDelete behavior can be used
      $manager->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, true);
  }
}
```

**Comment by alex-pex** [comment]
@j0k3r I don't see any mention of this new behavior in the docs nor in the code. Did you close this issue without any change ? It is not obvious that configureDoctrine is not called anymore.

**Comment by j0k3r** [comment]
@alex-pex woops sorry, closed to quickly, I thought @cburyta had given a workaround so that I can close the issue.

And yes `configureDoctrine` was removed https://github.com/LExpress/symfony1/commit/87410a11e0b60cdaf3bab8066da804421563aa4a and you know have to use the `doctrine.configure` event.
I'll update the doc accordingly.
