### ISSUE TITLE
Error in sfForm.class.php for embedded form

### ISSUE THREAD

**Issue by mirkz84** [LExpress/symfony1#56]
I found an issue at line 463 of sfForm.class.php.
In the original file (symfony 1.4.20) was:
$this->validatorSchema[$name] = $form->getValidatorSchema();
now is:
$this->validatorSchema[$name] = new sfValidatorPass();

It cause an error in configure functions of form classes when you try to set validator options of an embedded form.

**Comment by VanTanev** [comment]
@GromNaN wanted to second this.

The modification to `sfForm::embedForm()` that removes the validator schema of the embedded form is not only a huge BC break, it's also undocumented. I also fail to see the reason why embedded forms get their validators stripped - are we supposed to move sub-value validation to the main form? Then what would even be the reason to use an embedded one?

Please, consider reverting this behavior.

**Comment by alrayyes** [comment]
+1 Is there a workaround for this?

**Comment by jeromemacias** [comment]
@VanTanev Embedded forms did not get their validators stripped. Instead, main form call the sub form, wich handle validation himself.

It's a (not huge) BC break, that we did'nt see, and I'm sorry for that.

**Comment by VanTanev** [comment]
@jeromemacias Validation defined on embedded form objects is not executed when you execute the validation on the hosting form. This is very much a (huge) BC break. It's also easy to verify.

**Comment by clicproxy** [comment]
Hello, 

I'm actually have a problem with this sfForm update. 

The error message : 
`Fatal error: Uncaught Error: Call to undefined method sfValidatorPass::setPostValidator()`

Here's the code from the Form class : 

```
//form/doctrine/UtilisateurForm.class.php

$userStationForm = new UtilisateurStationForm($this->getObject()->getCodeStation());
$this->embedForm('code_station', $userStationForm);

// [...]

$this->validatorSchema['code_station']->setPostValidator(new sfValidatorAnd(array(
    new sfValidatorCallback(array('callback' => array($this, 'checkUniqueCodeByUserAndCountry'))),
    new UtilisateurStationValidatorSchema(),
)));
```


I do not know actually how to ajust this code with this new framework version. Can you help me solve this ?

Thanks for your support,
David.

**Comment by clicproxy** [comment]
The solution I've found : 

```
$this->validatorSchema->setPostValidator(new sfValidatorAnd(array(
    new sfValidatorCallback(array('callback' => array($this, 'checkUniqueCodeByUserAndCountry'))),
    new UtilisateurStationValidatorSchema(),
)));
```

And I've updated the checkUniqueCodeByUserAndCountry function to get values.
