### ISSUE TITLE
Doctrine error when Using submodules

### ISSUE THREAD

**Issue by austinh** [LExpress/symfony1#76]
Warning: require_once(/Doctrine/Core.php): failed to open stream: No such file or directory in /myproject/lib/vendor/symfony1/lib/plugins/sfDoctrinePlugin/config/sfDoctrinePluginConfiguration.class.php

This error message seems to be because express/symfony1 does not know where the new doctrine is.

**Comment by mstralka** [comment]
Hi, did you ever figure this out?

**Comment by mstralka** [comment]
Never mind - #51 notes that Doctrine was moved to a separate repo and can be required with composer.
