### ISSUE TITLE
preg_replace() the /e modifier is deprecated

### ISSUE THREAD

**Issue by xeux** [LExpress/symfony1#77]
Just to inform:

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in ----\lib\vendor\symfony\lib\util\sfToolkit.class.php on line 362

Replace:
return preg_replace(array_keys($replacePairs), array_values($replacePairs), $search);
With:
return strtr($search, $replacePairs);

**Comment by GromNaN** [comment]
Thanks for the report, but that would break code using regexp.

**Comment by xeux** [comment]
You are right, if you know how to fix this I will appreciate it.

**Comment by GromNaN** [comment]
I believe there is no regex with `/e` modifier in the code of lexpress/symfony1. So this error comes from your code. What is the full stacktrace ?

**Comment by xeux** [comment]
Sadly there is not a symfony trace, I get a plain PHP error:
Parse error: syntax error, unexpected 'Deprecated' (T_STRING), expecting '(' in C:\xampp\htdocs\gradin\lib\filter\doctrine\base\BaseEstudianteFormFilter.class.php on line 191

Then if I get to the line in the file I can see this:
public function add
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in ----\lib\vendor\symfony\lib\util\sfToolkit.class.php on line 362

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in ----\lib\vendor\symfony\lib\util\sfToolkit.class.php on line 362
VacunasListColumnQuery(Doctrine_Query $query, $field, $values)

You can see the PHP error it's appearing in some generated PHP code inside the base filter class

**Comment by xeux** [comment]
With your last comment, I understood what you are doing, I just checked the camelize method in sfFormFilterDoctrine.class.php, that will do the work. Genius!
