### ISSUE TITLE
Mettre à jour un vieux projet Symfony 1.4

### ISSUE THREAD

**Issue by guldil** [LExpress/symfony1#81]
Bonjour,

Bravo pour le travail déjà, ca semble tout bon :)

J'ai un vieux projet Symfony 1.4 que je souhaite migrer en 1.5 et migrer en PHP 5.5 (et tout ce qui suit). Ce projet n'a pas été crée avec composer au départ.

Quelle serait selon vous la meilleur solution pour migrer ?

Merci

Guldil

**Comment by j0k3r** [comment]
Ton symfony est installé où? Dans lib/vendor ou en dehors de ton projet ?

Concernant la migration, on a fait des choix techniques dans les formulaires imbriqués, que certains nous reprochent, #54, il faudra que tu vérifies ce point de ton côté du coup, pour valider que ça ne casse rien.

**Comment by guldil** [comment]
Oui il est dans lib/vendor
Pour les formulaires, je vais voir, je ne suis pas sur qu'il y en ait beaucoup et encore moins des imbriqués. A voir !

**Comment by j0k3r** [comment]
Et sinon pour *migrer* ton symfony, supprime ton `lib/vendor`, et exécute ces deux commandes:

```
composer require lexpress/symfony1 "1.5.*"
composer install
```

Depuis la racine de ton projet

**Comment by guldil** [comment]
Alors ca m'a crée un repertoire vendor à la racine et derriere rien ne marche :)
J'ai donc ajouté 
>require_once __DIR__.'/../vendor/autoload.php'; dans ProjectConfiguration.class.php et commenté 
>require_once dirname(__FILE__).'/../vendor/symfony/lib/autoload/sfCoreAutoload.class.php';
>sfCoreAutoload::register();

Là ca avance un peu mais j'ai doit à ; 

>\nFatal error: File not found: /Doctrine/Core.php in /home/guldil/prod/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/config/sfDoctrinePluginConfiguration.class.php on line 42

J'ai remis le vendor dans lib/ mais pas de changement...

Là j'ai compris qu'il me manquait lexpress/doctrine1 je l'ai donc ajout dans mon composer.json et j'ai fait un update, enfin dans le  ProjectConfiguration.class.php j'ai donc ajouté le sfConfig::set('sf_doctrine_dir', '/home/guldil/prod/vendor/lexpress/doctrine1'); et là çà avance !

Enfin presque car il cherche veut pas de mes appels Doctrine:: il semble vouloir Doctrine_Core::
Si je le remplace dans le code, çà fonctionne mais j'ai pas "envie" de le faire partout surtout que normalement il y a une classe Doctrine qui doit faire le travail d’étendre Doctrine_Core mais je la trouve pas... 

Une idée ?

**Comment by j0k3r** [comment]
Autant pour moi, il faut que tu précises ça dans ton composer.json:

```
    "config": {
        "vendor-dir": "lib/vendor/"
    },
```

Pour l'autoload, il faut que tu mettes:

```php
require_once dirname(__DIR__).'/lib/vendor/autoload.php';
```

Et concernant `Doctrine::` c'est une evol' côté Doctrine, il faut que tu les changes tous en `Doctrine_Core::`

**Comment by guldil** [comment]
J'ai triché pour Doctrine en mettant dans mon ProjectConfiguration.class.php : 
`class Doctrine extends Doctrine_Core`
`{`
`}`

Et çà fonctionne :) mais bon c'est pas top ...

**Comment by j0k3r** [comment]
Sinon tu fais un rechercher / remplacer et hop.
