### ISSUE TITLE
Adapts the Symfony2 DI Container 

### ISSUE THREAD

**Issue by issei-m** [LExpress/symfony1#82]
Why not use the Symfony2 DI Container as project DIC? I think that one is more powerful and flexible than `sfServiceContainer`.
In spite of there are also other useful DIC in PHP world (e.g. Pimple), introducing the new one by reinventing the wheel does not make sense.
Can you introduce Symfony's DIC as project DIC? I REALLY hope that you consider about this :)

**Comment by j0k3r** [comment]
We can think about it. But it won't be in the near future.
You can still try on your side and submit a PR :smiley:

**Comment by GromNaN** [comment]
You should try this plugin: https://github.com/hostnet/hnDependencyInjectionPlugin

**Comment by issei-m** [comment]
@GromNaN Thanks. I'll try this :smiley:
