### ISSUE TITLE
ZipExtract Error  with composer install on Windows.

### ISSUE THREAD

**Issue by tofuwarrior** [LExpress/symfony1#83]
When you try to do a composer install on windows it throws an error with the zip extraction. There is no useful error message but googling suggested it is because of a long path names issue on windows. (I'm using Win 7, WAMP server 2, php 5.5.12 )
Workround was to move the project folder up to the drive root and run it there where it worked fine.
Bit of a faff but not too onorous.
Could this be flagged up or could a more useful error message be generated to save others the time tracking this down?

**Comment by j0k3r** [comment]
Sadly this is an issue on Composer itself.

See (after a fast search on Google) https://github.com/composer/composer/issues/3755

**Comment by tofuwarrior** [comment]
Yes, but can it be documented in the setup so it is obvious what the 'solution' is, took me quite a while to sort this out.
Thought it would be easy to add into the read me as a footnote.

**Comment by GromNaN** [comment]
Can you submit a PR ?
