### ISSUE TITLE
broken version of SwiftMailer in composer.json

### ISSUE THREAD

**Issue by o-m-d** [LExpress/symfony1#89]
After upgrade project to sf1.5.3 I'm get a error: ```PHP Fatal error:  Class 'Swift_Encoding' not found...```
I'm search this class in all files but anything found.
I'm look SwiftMailer repository and found that the file ```lib/classes/Swift/Encoding.php``` with this class was deleted in v.5.2.1 and restored in v.5.3.0 - https://github.com/swiftmailer/swiftmailer/commit/52797f2246f4f784d9699beff03ef5c8bd51df7a

SwiftMailer version 5.2.2 is mandatory or it can be replaced by newer version?

**Comment by j0k3r** [comment]
Well, I think we can jump to `~5.2` in composer.json.

What do you think @GromNaN ?

**Comment by GromNaN** [comment]
@o-m-d Can you check https://github.com/LExpress/symfony1/pull/90

**Comment by o-m-d** [comment]
@GromNaN, SwiftMailer-5.4.1 installs and that error no longer occurs. Thanks.
